name: Dependabot Auto-Review and Label

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
      - main

permissions:
  contents: read
  issues: write        # Explicitly grant write access to issues for labeling
  pull-requests: write # Needed for auto-approving

jobs:
  auto-approve-and-label:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Versions From Commit Message
        id: commit_msg
        run: |
          COMMIT_SHA=$(jq -r '.pull_request.head.sha' "$GITHUB_EVENT_PATH")
          COMMIT_MSG=$(git log --format=%s -n 1 $COMMIT_SHA)

          versions=$(echo "$COMMIT_MSG" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
          read -r current new <<< "$versions"
          echo "CURRENT_VERSION=$current" >> $GITHUB_ENV
          echo "NEW_VERSION=$new" >> $GITHUB_ENV

      - name: Classify Dependabot PR
        id: classify_pr
        run: |
          if [[ -z "${{ env.CURRENT_VERSION }}" || -z "${{ env.NEW_VERSION }}" ]]; then
            echo "No version information found in commit message. Defaulting to high risk."
            echo "RISK=high" >> $GITHUB_ENV
            exit 0
          else
            IFS='.' read -r c_major c_minor c_patch <<< "${{ env.CURRENT_VERSION }}"
            IFS='.' read -r n_major n_minor n_patch <<< "${{ env.NEW_VERSION }}"
            if [[ "$c_major" -eq "$n_major" && "$c_minor" -eq "$n_minor" ]]; then
              echo "Patch update detected. Safe to auto-approve."
              echo "RISK=low" >> $GITHUB_ENV
            else if [[ "$c_major" -eq "$n_major" && "$c_minor" -lt "$n_minor" ]]; then
              echo "Minor update detected. Safe to auto-approve but requires maintainer review."
              echo "RISK=medium" >> $GITHUB_ENV
            else
              echo "Major update detected. Requires manual review."
              echo "RISK=high" >> $GITHUB_ENV
            fi
          fi

      - name: Auto-approve Dependabot PR
        id: auto_approve_pr
        # Only auto-approve if the risk is low or medium
        if: ${{ env.RISK != 'high' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE',
              body: 'Automatically approved by GitHub Action for Dependabot PRs.'
            });
            console.log('Dependabot PR approved successfully.');

      - name: Add labels if necessary
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          sync-labels: true
