name: e2e

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize 

permissions:
  contents: read

env:
  COMPLYTIME_DEV_MODE: 1

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Install the dependences
        run: dnf install git wget make scap-security-guide go tree -y

      - name: Build complyctl and init complyctl
        run: |
          git config --global --add safe.directory /__w/complyctl/complyctl
          sh tests/build_init_env.sh

      - name: Run e2e tests
        run: go test tests/e2e/e2e_test.go -v
