name: e2e-test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize 

permissions:
  contents: read

env:
  COMPLYTIME_DEV_MODE: 1

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      # Build and setup complyctl
      - name: Setup compyctl
        uses: ./.github/actions/setup-complyctl
        # This is the test data for a specific product, and it may be updated in the future if necessary.
        with:
          product: 'fedora'
          catalog: 'cusp_fedora'
          profile: 'fedora-cusp_fedora-default'

      # Run e2e tests
      - name: Run e2e tests
        run: go test tests/e2e/e2e_test.go -v
