name: integration-test

on:
  push:
    branches:
      - main
  pull_request:

env:
  COMPLYTIME_DEV_MODE: 1

permissions:
  contents: read

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # Setup complyctl for further testing
      - name: Setup compyctl
        uses: ./.github/actions/setup-complyctl
        # This is the test data for a specific product, and it may be updated in the future if necessary.
        with:
          product: 'fedora'
          catalog: 'cusp_fedora'
          profile: 'fedora-cusp_fedora-default'

      - name: Test complyctl list
        run: |
          # Set the -o pipefail option to ensure the step fails if grep fails 
          # set -o pipefail
          LIST_OUTPUT=$(complyctl list --plain)
          echo $LIST_OUTPUT
          echo $LIST_OUTPUT | grep -q "cusp_fedora"

      - name: Test complyctl plan
        run: |
          complyctl plan cusp_fedora

      # Validate OSCAL assessment-plan using go-oscal
      - name: Validate assessment-plan
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # download go-oscal executable
          gh release download --pattern "go-oscal_*_Linux_amd64" -R defenseunicorns/go-oscal
          GO_OSCAL_EXECUTABLE=$(ls | grep go-oscal)
          chmod +x $GO_OSCAL_EXECUTABLE
          # validation 
          ./$GO_OSCAL_EXECUTABLE validate -f complytime/assessment-plan.json 

#      - name: Test complyctl generate
#        run: |
#          complyctl generate
#
#      - name: Test complyctl scan
#        run: |
#          complyctl scan
