name: integration_test.yml

on:
  push:
    branches:
      - main
  pull_request:

env:
  COMPLYTIME_DEV_MODE: 1

permissions:
  contents: read

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # Setup complyctl for further testing
      - name: Setup compyctl
        uses: ./.github/actions/setup-complyctl
        with:
          catalog_path: 'catalogs/cusp_fedora/catalog.json'
          profile_path: 'profiles/fedora-cusp_fedora-default/profile.json'
          component_definition_path: 'component-definitions/fedora/fedora-cusp_fedora-default/component-definition.json'

      # Test complyctl
      - name: Test complyctl
        run: |
          complyctl list --plain
