---
name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.go'

permissions: read-all

jobs:
  generate-coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run test
        run: make test-unit
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage
          path: coverage.out
  sonarcloud:
    if: ${{ github.event.pull_request.base.repo.url == github.event.pull_request.head.repo.url }}
    needs: generate-coverage
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Get coverage
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@2500896589ef8f7247069a56136f8dc177c27ccf # v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.go.coverage.reportPaths=coverage.out -Dsonar.projectKey=rh-psce_complytime -Dsonar.organization=rh-psce
